[package]
name = "ollama"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1"
futures = "0.3"
http-client = { git = "https://github.com/fdionisi/http-client", version = "0.4" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
